### ISSUE TITLE
Stationary Zone Gone

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#110]
Hello,

I'm on beta 15 and HA 2023.4.6. I just noticed that my stationary zones don't seem to exist anymore. I think they worked on 2023.3 but I'm not positive. I don't see any logs showing errors, but the zones don't exist in my list of zones and my device trackers never go into a stationary state. Looking at the ic3 logs it looks like its being created, but it isn't. 

![image](https://user-images.githubusercontent.com/1593391/234371846-e8b3946f-936b-466f-87c4-595b3c91390f.png)

**Comment by gcobb321** [comment]
See if it is checked on the Configuration Wizard > Special zones screen. If it isn’t, they are not created or used. 

Btw, I have rewritten the Stationary Zone for b16. They are not associated with a device anymore so a StatZone can be shared by all devices in the same location. Also  the dev-trkr and people entities will show the correct stat zone instead of icloud3 showing the devices zone and the ha entities showing another devices StatZone. There are also created when they are needed

**Comment by broyuken** [comment]
it is checked and it did work on a previous version of HA. I THINK it was the 2023.4 update that broke it but I wasn't paying close enough attention.

**Comment by gcobb321** [comment]
Lets see if b16 fixes it

**Comment by gcobb321** [comment]
Stat Zones rewritten in b16

**Comment by broyuken** [comment]
Can we reopen this one? Stationary zones worked again after a full reboot, but I have a complaint about the new way these are set up. If I'm stationary, I want it to say stationary, not StatZon1 or even Stationary 1. I don't care which stationary zone I'm in, I just want to know if I am stationary. Please give us the option to decide if we want to append a number to the stationary zones or if we just want to keep it the way it's always been. 

Maybe provide some variables we can use to define the name of the zones?
#num inserts a number at the end or wherever we place the variable
#name inserts the device trackers name

For example
Stationary #num

**Comment by gcobb321** [comment]
Right now, if # is in the zone name, I insert the number. If not, I added it on. I’ll just remove the ‘add it on’ code. That way, you have the flexibility to do it either way. Using the device name won’t work because now multiple devices can use the same zone. If the device that made the zone leaves, it still has to exist if other devices are also using it.

I’ll update b16b when I get home. I’m hoping to upload that this afternoon.

Gary

**Comment by broyuken** [comment]
ah makes sense. I currently have some views and automations that use the stationary zone as a trigger or display item, and Stationary 1 looks funny, and also makes triggers more difficult for automations and whatnot. Be more than happy to test when its ready, but since I've been testing this since you first released the betas it's come a LONG way. The only part I really had issues with was the migration from 2->3, but if those are ironed out or if you want to have people install it as a new integration altogether then I think we're right around the corner from a full release.

**Comment by gcobb321** [comment]
I just ran a bunch of errands and found the stationary zone was not getting set, the timer was not triggering but that is all fixed now. Also, the number is only inserted into the name to replace the '#' wildcard, no '#', no number.

To trigger StatZones when testing, I move the Home zone gps longitude value from -80 to -81. That brought up another question. At that location, the interval becomes 1.8hrs. If I set the max_interval to 45min, the interval becomes 45min. Now the question...If the StatZone inzone interval is 30 min and the normal interval is more than that, should the Device be moved into the StatZone at all. I'm thinking it should not be sine that defeats the purpose of the StatZone. What do you think?
