### ISSUE TITLE
battery status no longer updating

### ISSUE THREAD

**Issue by JtwoA** [gcobb321/icloud3_v3#124]
With the move to 16/16a the battery status (charging/not charging) appears to have stopped working.

**Comment by FredWst** [comment]
In my case 16a working, but 16b not working.

Fred

**Comment by gcobb321** [comment]
I just plugged in my iPhone. The iOS App picked it up within 5-secs, changed the icon and added the BatteryLevel-95%, Charging (iOS AP) to the Event Log. Is your device using the iOS App?

**Comment by JtwoA** [comment]
It is using the app and was working flawlessly up to this change, hence why I pointed to the update.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by gcobb321** [comment]
Understand.

Beta 16b - 5/10/2023 (11:07:33am US EDT)
...................
1.  Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked, the update was not being processed since the data had not changed when it should have been processed on the initial trigger.

2.  Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.

3.  Configuration Wizard - Fixed a problem displaying the 'Next Page' on the Update Devices and Display-Text As screens.
Here is an updated b16b

[icloud3_v3-beta-16b.zip](https://github.com/gcobb321/icloud3_v3/files/11443491/icloud3_v3-beta-16b.zip)

**Comment by filikun** [comment]
Hmm I'm having this issue as well. The app is used on the phone and everything else works but It does not report battery and have never done that.

**Comment by gcobb321** [comment]
What is the battery sensor entity name you are looking for?
It’s battery checked on the Configuration Wizard > Sensors screen?
Set log level to Debug and restart HA. All the sensors that are created are listed in _icloud-debug.log_ file. 
The entity name is _sensor.[devicename_battery_. Mine is _sensor.gary_battery_.
