### ISSUE TITLE
Data not accurate

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#13]
Hi all,

I checked If the data that has been received is accurate. Its not. My friend is at Ziggo Dome for BlackPink Concert but his location is still at his work. I check find my friends and live view is in Ziggo Dome.

The information from iCloud3 is still at his work...

**Comment by gcobb321** [comment]
Without an error message or programming exception message, it is probably a data change issue rather than a program problem. It sounds like iC3 did not get a trigger to update the devices location. This can be caused by no OS App exit zone trigger or the next location update time had not been reached so iC3 had nor requested a new location. A poor cell area can also generate errors and the device has been paused. The Event Log should show what is going on. Using Event Log > Actions > Show Tracking Monitors can give more detailed info.
