### ISSUE TITLE
Errors logged in Home Assistant Beta 2023.6.0b

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#144]
Errors in current home assistant beta.
Python version problem ?

```
2023-06-02 07:41:07.457 ERROR (MainThread) [icloud3] 'function' object has no attribute '_exclude_e'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 420, in __init__
    ha_history_recorder.entity_filter._exclude_e.add(self.entity_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_exclude_e'
2023-06-02 07:41:07.460 ERROR (MainThread) [icloud3] 'function' object has no attribute '_exclude_e'
```

**Comment by criticallimit** [comment]
same here:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: icloud3
Source: custom_components/icloud3/sensor.py:420 
Integration: iCloud3 v3 (documentation, issues) 
First occurred: 15:31:04 (6 occurrences) 
Last logged: 15:37:48

'function' object has no attribute '_exclude_e'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 420, in __init__
    ha_history_recorder.entity_filter._exclude_e.add(self.entity_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_exclude_e'
```

**Comment by B-Hartley** [comment]
Developer (Gary) said on same bug in icloud3 main repository:

The HA guys must have changed the history component and removed the hack I was using to exclude some of the iCloud3 sensors from being added to the history data base. I just installed 2023.6.0.b2 and saw it. I’m out of town until next week and will post a fix then.

https://github.com/gcobb321/icloud3/issues/267#issuecomment-1573646125

**Comment by gcobb321** [comment]
I have found code in other HA components that use a different way of implementing the recorder filter. It helps that I am also getting the sane error.

**Comment by gcobb321** [comment]
Beta 18 fixes this. I'll publish it is a few days if everything looks OK.

Unzip to the icloud3 directory
[icloud3_v3-beta-18.zip](https://github.com/gcobb321/icloud3_v3/files/11750220/icloud3_v3-beta-18.zip)

Change Log:
1.  Event Log - Fixed a problem where displaying a Nearby Devices message would display the text below the Event Log items window due to a HA Front End change.
2.  iOS App Only - Location requests will be sent to the device when the iOS App is the primary data source just like it is to the iCloud Web Service. This only sends a request to the iOS App. If the device is asleep or the iOS App is running in the background or not loaded, it will not respond and send the location. In this case, another location request will be sent when the next update time is reached.
3.  StatZone - Do not create a Stationary Zone when the current location data is old.
4.  History Recorder - Fixed the problem leading to the '_exclude_e' not being found error while adding iCloud3 HA Recorders sensors to the exclude_entities list.
5.  icloud3_debug_log file - Changed the name to 'icloud3-0.log' since it now contains a lot more info than just debug entries. Three generations of the log file will be kept, indicated by the suffix ('-0'=Today, '-1'=Yesterday, '-2'=Two days ago).
6.  Device Verification during startup - When starting up, device data/location information is used to verify the device. If the iCloud Location Service does not respond with location data for one or more devices during startup, the verification process is now automatically retried several times. If it still fails for one or more devices, a restart is needed message is displayed to try again later. The verified devices will continue to be tracked.
7.  Configuration Wizard - Change the range of the inzone interval parameter values from 5-240 minutes to 1-300 minutes.

**Comment by marceloaf** [comment]
Hi, Gary.

I tried beta 18 but the startup process never finishes. Seems it loops between stages 4 and 5. I tested in HA 2023.5.4 and 2023.6.1

I won’t be able to send logs right now but I’ll do it tomorrow morning.

Cheers,
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by JtwoA** [comment]
I've just deployed and everything looks good. Adjusted Watch inzone to 1:00 just to test and everything saved, updated, etc. just fine.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by gcobb321** [comment]
@marceloaf  it tries to get all iCloud devices 10 times by restarting Stage 4. It then continues with Stage 5 and then tries Stage 4 and 5 again 2 times and then gives a restart is needed message. At least that is what it’s suppose to happen. I had to simulate several things during testing. I’ll add some retry messages and post an update sometime tomorrow. Maybe that will shores where it is looking. A timing issue I suspect.

**Comment by gcobb321** [comment]
Fixed in beta 18
