### ISSUE TITLE
'function' object has no attribute '_exclude_e'

### ISSUE THREAD

**Issue by romlisrl** [gcobb321/icloud3_v3#147]
Home Assistant 2023.6.0
Supervisor 2023.06.1
UI 20230607.0 - latest
iCloud3 v3, beta 17 (5/28/2023)

Logger: icloud3
Source: custom_components/icloud3/sensor.py:420
Integration: iCloud3 v3 (documentation, issues)
First occurred: 09:23:38 (12 occurrences)
Last logged: 09:23:38

'function' object has no attribute '_exclude_e'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 420, in __init__
    ha_history_recorder.entity_filter._exclude_e.add(self.entity_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_exclude_e'

**Comment by gcobb321** [comment]
Working on it. The HA guys changed the way sensors are excluded from the Recorder history database and I’m trying to figure it out now.

**Comment by gcobb321** [comment]
This has been fixed in beta 18. Attached is a preliminary copy for you to try. I'll publish it in a few days if you don't see any problems.

Unzip to the icloud3 directory
[icloud3_v3-beta-18.zip](https://github.com/gcobb321/icloud3_v3/files/11750200/icloud3_v3-beta-18.zip)

Change Log:
1.  Event Log - Fixed a problem where displaying a Nearby Devices message would display the text below the Event Log items window due to a HA Front End change.
2.  iOS App Only - Location requests will be sent to the device when the iOS App is the primary data source just like it is to the iCloud Web Service. This only sends a request to the iOS App. If the device is asleep or the iOS App is running in the background or not loaded, it will not respond and send the location. In this case, another location request will be sent when the next update time is reached.
3.  StatZone - Do not create a Stationary Zone when the current location data is old.
4.  History Recorder - Fixed the problem leading to the '_exclude_e' not being found error while adding iCloud3 HA Recorders sensors to the exclude_entities list.
5.  icloud3_debug_log file - Changed the name to 'icloud3-0.log' since it now contains a lot more info than just debug entries. Three generations of the log file will be kept, indicated by the suffix ('-0'=Today, '-1'=Yesterday, '-2'=Two days ago).
6.  Device Verification during startup - When starting up, device data/location information is used to verify the device. If the iCloud Location Service does not respond with location data for one or more devices during startup, the verification process is now automatically retried several times. If it still fails for one or more devices, a restart is needed message is displayed to try again later. The verified devices will continue to be tracked.
7.  Configuration Wizard - Change the range of the inzone interval parameter values from 5-240 minutes to 1-300 minutes.
