### ISSUE TITLE
iCloud3 v3 HACS can now be used to install a new release

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#154]
HACS lives again. I have found and fixed the config issues and have done an update. Go [here](https://github.com/gcobb321/icloud3_v3/issues/129#issuecomment-1600510073) for more info.

**Comment by criticallimit** [comment]
Thant´s good news! Thanx for your hard work.

But I have a request:
Acually the user would be confused about the naming of the releases. It would be a good solution to follow a strict Main and Beta wording. 

![Bildschirmfoto](https://github.com/gcobb321/icloud3_v3/assets/5613811/28d99c92-44db-4f93-8a31-b4061c319f47)


On the picture you can´t see which is actual beta or release version because of some different beta wording (is it the correct english word?) 
User has to assume that first value is actual value?
Strict forward wording in Beta and Release Versions would be helpful 

;-)

**Comment by gcobb321** [comment]
I since it is in beta, the main has always been v3.0.0bx. The beta has followed the convention of a normal number for it's release, b1, b10, b17, b18. There were times when there was one or two easy to fix issues with that beta. They have followed a letter suffix 16a, 16b, 16c. With b18, I released it privately to a number of users without posting a release. They got 18a, 18b so the first general b18 release was 18c & 18d. I finally worked out the HACS issues and have decided to follow the b18.5 convention for other reasons (instead of b18e). Thanks for your thoughts but it's under control and any more major beta will be b19, b20 with minor ones being b19.#.

I now consider the code frozen except for problems (and maybe one think I want to look at regarding translations) and should ditch the beta designation and go to rc1 (release candidate 1). That will happen when I get several hundred using iw with no issues. It will then go to the v2 icloud repository as a pre-release. Then a full release. Yesterday v2 had 8871 downloads and I'm one guy with other stuf to do. I don't want to be slammed with questions and issues.

Thanks for trying it and let me know if you run into anything.

Gary
