### ISSUE TITLE
new log file not being created per the new behavior definitions.

### ISSUE THREAD

**Issue by pauly7300** [gcobb321/icloud3_v3#19]
Per the beta 4 log file rework...
Reworked the icloud3-debug.log file:
- A new file is created when:
1. HA/iCloud3 starts and the Log Level is debug or rawdata or
2. Starting Debug Logging from Event Log > Actions or
3.  At midnight when debug logging is on and the file is more thn 20-hours old.
- Otherwise debug records are added to the existing Debug Log file.
- If the Log Level is debug or rawdata in the Configurator > Event Log parameters and
Stop Debug Logging was selected on Event Log > Actions, the ic3 config will be changed
to 'info' (no debug logging).
- If the configuration is set to 'info' (no debug logging) and it is started on
Event Log > Actions, the configuration is not updated and the debug logging will
remain on until midnight, the next iCloud3 restart or when it is turned off.

In Beta5 I can't seem to cause a new log file to be created by either method 1 or 2 from above.  It seems as if a new log file will not be replaced until it is at least 20 hours old and midnight has passed.

**Comment by gcobb321** [comment]
The icloud3-debug.log file will now always be a new file when starting HA or restarting ic3 from the Event Log > Actions. It also create a new file if starting debug logging from Event Log > Actions and the file is less than 20-hours old. If more than 20-hours old, it will create a new one.

Thanks...fixed in beta 6
