### ISSUE TITLE
Add on

### ISSUE THREAD

**Issue by gieljnssns** [gcobb321/icloud3_v3#198]
Isn't it possible to make an addon for icloud3?
So the core of icloud3 runs on its own?
Just as Music Assistant did, at first it was all part of one HA integration, but they took the core of MA apart.
iCloud3 makes the startup of HA a lot slower...

**Comment by gcobb321** [comment]
iCloud3 v3 itself starts a lot faster than v2. It spawns a number of tasks that all run at the same time when starting up. Any slowness is caused by trying to do the intitial locate of the devices where Apple has to locate them and then provide the location information back to iCloud3. When Apple does this, it gets the location for all the devices in the family sharing list, not just the tracked ones.
