### ISSUE TITLE
unable to get the 6 digits again

### ISSUE THREAD

**Issue by snhnic** [gcobb321/icloud3_v3#202]
Driving me nuts. the 6 digits where wrong and teh integration does not resend!

**Comment by gcobb321** [comment]
Configure Settings > Enter/Request Verification Code screen. Request a new code, then enter it on this screen

**Comment by snhnic** [comment]
That’s the problem. Nothing happens. So it’s not closed!

**Comment by JtwoA** [comment]
> That’s the problem. Nothing happens. So it’s not closed!

Logs?  What do the logs say?

**Comment by gcobb321** [comment]
@snhnic 
Like JtwoA said, are you getting any errors in HA? Any errors in _icloud3-0.log_ or _home-assistant.log_?
Was your iPhone tracking before? Have you just changed iPhones or is this the phone you used to verify before? I’m just trying to make sure the code is not being sent to another phone. 
Have you tried _Event Log > Actions > Request Apple ID Verification Code_?

If all else fails, rename the _config/.storage/icloud_ directory to something else and restart iCloud3 (_Event Log > Actions > Restart iCloud3_). That directory contains your web session authentication cookie files. 

Note:  You will also see the the _config/.storage/icloud3_ directory that contains the iCloud3 configuration files. Don’t do anything with that directory. 

BTW, Your original question did not say you had already tried requesting a new code. I get that question a lot because people do not know that you can request one.

**Comment by snhnic** [comment]
Yes you’re right. The cause is my new Iphone. After several tries it just popped up with a code. I think your right it was sending to the old phone. Maybe you can address this in the icloudv3 since it was not giving me any feedback if the reset was handled or not.
