### ISSUE TITLE
Using Nearby Device Results

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#227]
One of my family iPhones is saying it's at home when it's not.

In the log it says:

```
16:31:32           Service Action Received > Action-locate
16:31:32           Service Action > Action-Locate This Device (FamShr, FmF), Device-ryans_iphone_ic3
16:31:32           Location will be updated at 16:31:35
16:31:35           Located > iOSApp-00:00:00/±9m (FamShr-16:08:27)
16:31:35           Trigger > Next Update Time Reached
16:31:35        │  Zone > Home-4m (3) > NotSet (2), London (1), GPS-(51.xxxxx, -0.0xxxxx/±9m)
16:31:35        │  Nearby Devices > (&lt;20m), ✓Derek`s iPhone (IC3)-2m, ✓Lindsey`s iPhone (IC3)-2m, >Lauren`s iPhone (IC3)-
                        │               15.2km, ×Alan`s iPhone (IC3)-0m, ×Sylvie`s iPhone (IC3)-0m
16:31:35        │  Using Nearby Device Results > Lindsey`s iPhone (IC3), Distance-2m
16:31:35        │  DirHist-ZZZ
16:31:35        ├─ Results: From-Home > NextUpdate-16:46:35, Interval-15 mins, Moved-4.52km
»Home           │  iOSAppState-Home, iCloud3Zone-Home, Interval-15 mins, TravelTime-, Distance-
                        └─ iOSApp Results > Next Update: 16:46:35
16:31:35           Device Monitor > famshr, Next Update Time Reached, AttrsZone-home, LocDataZone-home, Located-00:00:00 (0
                                        min ago), iOSAppGPS-(51.xxxxx, -0.0xxxxx/±9m), iOSAppState-home), GPS-(51.xxxxx, -0.0xxxx/±9m)
16:32:25           Service Action > Action-Export Event Log, Device-ryans_iphone_ic3
```

From what I can see, it says that this is using the Nearby Device Results for being 2m from Lindsey's iPhone. However, if I look at Lindsey's iPhone it says it is 4.5km from Ryan's iPhone. If I look at Ryan's iPhone, it says it is 2m from Lindsey's iPhone.

If I go into FindMy on my iPhone, it shows the correct location for Ryan's iPhone.

Any idea why it's not correctly identifying the location for Ryan's iPhone? (but it is for all others).

**Comment by derekoharrow** [comment]
I've turned off Nearby Tracking and still no change - I'll send you the log shortly.

**Comment by gcobb321** [comment]
I've wrapped up rc9. Here is a preliminary copy with the code that addresses the problem you had, along with a bunch of other things.  I have not uploaded this to GitHub yet but probably will this coming Wednesday. Let me know how things go (ok or there is a problem).

Unzip icloud3-rc9.zip into the icloud3 directory and restart HA.
[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3/files/13467440/icloud3_v3-rc9.zip)

### rc9 Change Log:
1. Stationary Zone
    - Fixed a bug restarting iCloud3 when reinitializing the zones and a Stationary Zone already existed. Some of the zones were not reloaded and the Stage 2 Zone setup process would end.
    - All Stationary Zone information persists over iCloud3 restarts and devices that were in the Stationary Zones will be moved back into it.
    - Unused Stationary Zones will be  checked and deleted every hour
    - A nearby device results will not be used if the device's stationary zone timer has expired
2. The iOSApp Location Time was not being saved correctly when it processed an update handling the Initial Location  triggers when starting iCloud3.
3. Bug fix - Devices that were paired with a Watch that was not being tracked were displaying a message in the Event Log that they were paired with themselves.
4. Battery - Fixed a problem so the battery sensor would only be updated when the battery level or status changed. It was updating when the information hadn't changed which was causing excessive and unnecessary HA battery sensor state changes.
5. Near zone (home) old location update retries - When approaching Home, the location request time was small (15-secs) and old location info was being returned from iCloud, the old location threshold was set to 15-secs to try to get a good location.  This sometimes resulted in the location always being old even when it was good enough to be used. Now, the small interval will only be used for 4 Location requests.  The old location threshold of 2-3 minutes will  then be used.
6. Waze History Database - Removed some maintenance activities being done when iCloud3 starts that was delaying the startup process by almost 2-minutes for a database with 10,000+ entries. This is now done at midnight.
7: Event Log - The Event Log items are displayed a lot faster after selecting a different device or refreshing the screen.
8. HA Area - iCloud3 was assigning or reassigning the tracked and monitored devices to the 'Personal Device' area when starting. This will now only be done when the devices is added or changed from Inactive to Tracked. You can now change or delete the device's HA Area and it will not be reassigned.

9. NEW FEATURE - Away Time Zone - "The time displayed in the Event Log and Sensors show the time an event took place using the Home 'time zone' from your Home Assistant computer.  When you are away from Home and in another time zone, your tracking events are still based on the time at your Home 'time zone', not time in your current location. This feature lets you display time events on the Event Log, Sensors, Sensor Attributes and the Device_Tracker Attribures using your Away location's time zone.

This is useful if you are away for a holiday or business trip to a location in another time zone. For example, you may create a temporary zone for a house you rented, set that zone up as a 'track from' zone on the device's update screen and then all time based tracking events (arrival time, location time, etc) will show your local time instead of your Home time zone time.

The Away Time Zone screen has been added to the Configure Settings, Menu Page 1. On this screen, you can configure the devices that should display the time based entities in the Away Time Zone and the Away Time Zone's time. Two configuration fields are provided if you have several devices that are away and they are in different time zones.

10. NEW FEATURE - Log Activity for Zones - When a device exits a zone, the zone information (Enter Time, Exit Time, Time in the Zone (minutes & hours), zone name and device_name) can be written to a spreadsheet .csv file. This file can be imported into a spreadsheet (Excel, etc) and used for travel expense reporting, monitoring when a device entered and exited a zone, who entered a zone, etc. The zones and file name format is specified for each device you want to monitor. You can monitor multiple zones for one or more devices.

The file name format is:
    - 'zone_log-[year]-[zone]' to store the data by a specific zone for multiple devices. For example, you can keep records for Gary and Lillian in the Warehouse zone file.
    - 'zone_log-[year]-[device]' to store the data for a specific device for multiple zones. For example, you can keep records for Gary when he goes to the Warehouse and Storage Facility zones.
    - 'zone_log-[year]-[zone]-[device]' and 'zone_log-[year]-[device]-[zone]' to store the data for more than one device and more than one zone in the same file.  For example, you can keep records for Gary when he goes to the Warehouse zone in one file and Storage Facility zone in aqnother file. The two filename formats allow you to sort the spreadsheet file by device or by zone.

**Comment by derekoharrow** [comment]
Thanks - I'll give it a try today!

**Comment by derekoharrow** [comment]
Hi. I’m not at home so can’t send logs etc right now, but this version
doesn’t seem to be working properly at all - my own phone and my wife’s are
away from home but IC3 is saying we’ve been home for 3 days. My daughter is
home but it’s saying she isn’t. It doesn’t seem to be updating to match
FindMy at all really…

**Comment by gcobb321** [comment]
Hmmm. 
Do you see any errors when you go to HA Settings > System > Logs related to iCloud3?
Is the log level set to Debug on _Configure Settings > Page 2 > Format Parameters_ screen? That will help. You can do that and it takes effect immediately without a restart. 
Hopefully the logs will show what is going on.

**Comment by gcobb321** [comment]
I just had another user post an error message that would affect device 
tracking. It had to do with calculating the distance moved since the 
last update that determines if an update should be done. The error is:

"/config/custom_components/icloud3/support/icloud_data_handler.py", line 
238, in update_PyiCloud_RawData_data if (Device.moved_since_last_update 
< .0005):


I'll send you an update later today.

Gary Cobb (geekstergary)


------ Original Message ------
From "derekoharrow" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Gary Cobb" ***@***.***>; "Comment" 
***@***.***>
Date 12/1/2023 6:56:53 AM
Subject Re: [gcobb321/icloud3_v3] Using Nearby Device Results (Issue 
#227)

>
>Hi. I’m not at home so can’t send logs etc right now, but this version
>doesn’t seem to be working properly at all - my own phone and my wife’s 
>are
>away from home but IC3 is saying we’ve been home for 3 days. My 
>daughter is
>home but it’s saying she isn’t. It doesn’t seem to be updating to match
>FindMy at all really…
>

**Comment by gcobb321** [comment]
Derek,
I never received the files

**Comment by gcobb321** [comment]
I just looked at the log and this error is all over the place.

_2023-12-01 02:08:55 [icloud_data_:0163]  ICLOUD > lindseys_iphone_ic3 iCloud Location Request Error > An error occured refreshing the iCloud Location. iCloud may be down or there is an internet connection issue. iCloud3 will try again later. ('iCloud3_Device' object has no attribute 'moved_since_last_update')_

Here is the latest rc9 with that fixed. I also did made some changes. See below. The big change is handling the FamShr configuration during startup. Let me know if there is a problem with that.

Unzip rc9 as always.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13539653/icloud3_v3-rc9.zip)

**Changes after the last list:**
9. Battery Attributes - Add the last battery data for famshr and iosapp to the sensor.battery attribute list (45@11:10:55a, not charging).

10. Family Sharing Device list analysis during iCloud3 startup
   1. The configuratin FamShr device name will be updated if it's name was updated on the device Settings > General > About screen on the device.
   2. If a device's name is followed by a suffix (Gary-iPhone(2)), it usually means that the device has been upgraded and the old device was not removed from the Family Sharing list or the FindMy > Devices list. This can lead to confusion where an old device is being tracked if the iCloud3 configuration was not updated. If there is more than one device with the same 'base name' (Gary-iPad), an Alert message is displayed in the Event Log showing all devices with that name and the last time that device was located. The configuration is changed to the device most recently located and an alert symbol is displayed by the device's name on the Event Log. It will continue to be displayed until the duplicate devices have been removed from the FindMy > Devices and Family Sharing List.
  
11. Bug Fix - The 'moved_since_last_update_km' variable was removed in error in rc4 and may cause a device to not be tracked properly.

**Comment by derekoharrow** [comment]
Trying it now - will know more about how it performs in the morning. Thanks!

**Comment by gcobb321** [comment]
This is the latest that includes the fix for the dup devices check issue. we discussed earlier today. I also added some more debug_trace to the startup process.

Posted 12/4 4:45 EST
[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13551538/icloud3_v3-rc9.zip)

**Comment by gcobb321** [comment]
Here is the latest version of rc9 before I release it next week for you to try.

The final changes won't affect you but I wanted to make sure I didn't break anything.
One critical change is to the method of determining the time an iOS App trigger takes place and how time zones are handled. Check the Event Log to see if a Trigger or zone change time does not seem to match the event time.

Unzip rc9 and restart as always.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13693706/icloud3_v3-rc9.zip)

**Comment by derekoharrow** [comment]
> Here is the latest version of rc9 before I release it next week for you to try.
> 
> The final changes won't affect you but I wanted to make sure I didn't break anything. One critical change is to the method of determining the time an iOS App trigger takes place and how time zones are handled. Check the Event Log to see if a Trigger or zone change time does not seem to match the event time.
> 
> Unzip rc9 and restart as always.
> 
> [icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13693706/icloud3_v3-rc9.zip)

Thanks - testing it now...

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
