### ISSUE TITLE
Feature Request - distance between devices

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#23]
Hi, loving IC3v3 so far!

In the attributes for the device_tracker entities, it has an attribute of "Distance To", showing the distance from that device tracker to the other device trackers.

This is really useful info as it enables you to tell if two people are near each other. For example, I don't want certain actions to happen if my wife and I are together, etc.

Could you expose these as separate individual attributes perhaps to make them easier to consume? Or perhaps create different entities to track the distance between specific trackers?

Thanks

**Comment by gcobb321** [comment]
The distance to other devices is in the [devicename]_zone_distance sensor. It shows it by friendly name/device type in meters with the gps accuracy, which makes it a text field and hard to extract. The other distance attributes of this sensor also show the mi/km text rather than just the value. 

It would be easy to show distances without the mi/km which would make them all numeric, use the devicename instead of the friendly name and just show the distance without the gps accuracy. Your thoughts?

**Comment by derekoharrow** [comment]
Brilliant! I've crafted a template to extract just the distance - e.g.

`{{ state_attr("sensor.dereks_iphone_ic3_zone_distance","Lindsey's iPhone (IC3)/iPhone").split('/')[0][:-2] }}`

or

`{{ state_attr("sensor.dereks_iphone_ic3_zone_distance","Lindsey's iPhone (IC3)/iPhone").split('/')[0].split('km')[0] }}`

This returns the distance in km (without the km)

**Comment by diothar** [comment]
Love this idea, I'll test it out.

**Comment by gcobb321** [comment]
Added tobeta 7 [here](https://github.com/gcobb321/icloud3_v3/issues/2), Look at the __zone_distance and/or _home_distance sensor for each device.
