### ISSUE TITLE
„last located“ suddenly in the future

### ISSUE THREAD

**Issue by klingbing** [gcobb321/icloud3_v3#232]
hi!

First, thank you for all the work you are putting into this integration!

I‘ve only just started using the integration a couple of months/versions ago and had it working smoothly over a longer period. But suddenly the location of my iPhone is no longer being tracked properly (my wifes iPhone is being tracked just fine all the time). While trying to figure out what‘s wrong I noticed that my iPhone was last located in the future:

`zone: home
last_zone: work
zone_changed: "0000-00-00 00:00:00"
last_located: "2286-11-20 18:46:39"
last_update: "2023-11-21 18:48:25" `

I‘ve tried restarting the integration, also a reboot does not resolve.

I was unable to find similar issues from other users, so any help is kindly appreciated.

On a side note, the `zone_changed` attribute has not worked for any of our iPhones to date, it just stays at the 0000… above. I‘m not sure it‘s related.

**Comment by gcobb321** [comment]
The latest released beta. It’s rc8. Are you running that version?
Check the HA logs to see if there are any errors. HA Settings > System > Logs. 
Check the _Event Log_ for any error messages, anything wrong in the device parameters listed in Stages3-5 when iCloud3 starts and messages in the iCloud-0.log file.

**Comment by polskikrol** [comment]
Using the latest myself, 3.0.rc8 and looks like the Family tracking has stopped working for me. See an error such as the following post upgrade:
May Be Offline, LocTime-7:00:01p (19684.6 days ago), OldCnt-#20
So the time there is way off and appears to not poll the battery % or anything. It does update my own account devices fine, and no settings were changed on either phone in terms of allowing location sharing. I have enabled debugging this morning.

On another note, I updated HA and everything. So I ended up re-authenticating to iCloud. Checking the 'direction' entity history, I note that when I traveled away from home, my account was not authenticated, but it still shows as the location was home. Is there anyway to have a 'failsafe' or perhaps an option to state that 'direction' is unknown, rather than propagating the last known value. Meaning, think it would make sense to verify a device is actually home and post that status, rather than assume if polling stops due to authentication or anything.

**Comment by gcobb321** [comment]
1. Check the _Configure Settings > Update Devices_ screen to make sure the famshr device is linked to the your current phone. Make sure there are no duplicate devices with the same name or a new device with a (#) in the name. 
2. verify the device info on the _Event Log_ Stage 3, 4 and 5. That shows your configured devices and the data iCloud3 received from Apple during setup. 
3. Turn on Tracking Monitors _Event Log > Show Tracking Monitors_. This gives details about the data received from Apple. 
4. Make sure location Sharing on your phone is still on and you can see your phone on another device on the FindMy app > Devices

**Comment by polskikrol** [comment]
You may be onto something. The other phone which is sharing location services outside of the master account (used for auth) was upgraded to the newest iOS. Checking on the iPhone, the location services under devices shows THREE devices with the same name, and only one has the correct location/distance updated. Now, I am hesitant to remove these 2 extra instances as swiping left to trash can the object I receive a scary message -- "This iPhone is linked to your Apple ID. Removing this iPhone will allow it to be activated and used by another person." So I dismissed this idea. Going into the HA setting for iCloud3 as you outlined, I noticed something had changed! I had the tracking device selected as a 12 mini but it was changed to a 6 (an older phone still associated with the remote account, with the same device name). I definitely didnt have the 6 selected to begin with, as I was receiving the correct tracking data from the 12 mini (what I recall selecting). So not sure if the code is keeping tabs on the correct device by only the device name (which didnt change) or some other UID that is specific to that device. Meaning, not sure how this was 'magically' swapped to the older wrong device. Hope this info helps?

**Comment by gcobb321** [comment]
Do you see any errors in the HA logs (HA Settings > System > Logs)?
Did you get a new phone? You could still be tracking your old one if you did not change the configuration and the new one has a different name. 
Any messages in th _Event Log_ during start up?

**Comment by klingbing** [comment]
Hi Gary,

thanks for your reply, back to my original issue. I can confirm that I'm using the latest/RC8 version.

- No errors in the _Event Log_  
- iCloud-0.log: I scanned the file for "error" and stumbled over this:
`AttributeError: 'iCloud3_Device' object has no attribute 'moved_since_last_update'
2023-12-01 13:29:00 [icloud3_main:0311]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 263, in _polling_loop_5_sec_device
    self._main_5sec_loop_icloud_prefetch_control()
  File "/config/custom_components/icloud3/icloud3_main.py", line 569, in _main_5sec_loop_icloud_prefetch_control
    icloud_data_handler.update_PyiCloud_RawData_data(Device,
  File "/config/custom_components/icloud3/support/icloud_data_handler.py", line 238, in update_PyiCloud_RawData_data
    if (Device.moved_since_last_update < .0005):`

Could that have anything to do with the "last located" of my iPhone being in the future and "zone_changed:"  has "0000-00-00 00:00:00" since i started using iCloud3 for both our devices?

**Comment by gcobb321** [comment]
It could have. It could also lead to other tracking errors. I'll fix it and send you an update when ready, probably later today.

**Comment by gcobb321** [comment]
Below is the latest rc9 update. Unzip icloud3_v3-rc9.zip into the icloud3 directory and restart HA.

I think I've fixed this issue. Let me know if you run into anything.

There are a lot of updates, bug fixes and new features. Review ChangeLog.txt for a complete list. They are at the top under the rc9 heading.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13641390/icloud3_v3-rc9.zip)

**Comment by klingbing** [comment]
Hi Gary,

thanks! I installed rc9 as instructed, this did not resolve I'm afraid.

`zone_changed: 0000-00-00 00:00:00
last_located: 2286-11-20 18:46:39`

The previously mentioned error in iCloud-0.log seems to be resolved though (no longer in logs).

Unless you have any other ideas I would like to start from scratch and do a icloud3V3 reinstall. I already tried  by deleting the integration from HA -> Settings -> Integrations, but after a reboot and a reinstall the entities are back and

`zone_changed: 0000-00-00 00:00:00
last_located: 2286-11-20 18:46:39`

remains.

Apols if this is obvious or already documented, but how can I fully remove icloud3V3 in order to do a fresh install?

**Comment by gcobb321** [comment]
To nuke ic3, 
- Remove the Integration
- Delete the ic3 directory
- Reboot HA 2 times (yes 2 times)

If you want to delete the config, delete _config/.storage/icloud3_ directory. I. Would probably just rename it for note. Do not delete the _config/.storage/icloud_ directory. It contains the iCloud cookie files that allow access to your iCloud account data. If you do, you will need to go thru the authorization again.

**Comment by gcobb321** [comment]
The 2286-11-20 18:46:39 date converts to a time in seconds of -3600secs which is -1hr. Have you had any issues related to to Time zone differences on the devices or the time iCloud3 determines when it starts (time zone offset in the _Event Log_) or HA?

**Comment by klingbing** [comment]
> The 2286-11-20 18:46:39 date converts to a time in seconds of -3600secs which is -1hr. Have you had any issues related to to Time zone differences on the devices or the time iCloud3 determines when it starts (time zone offset in the _Event Log_) or HA? It’s almost like the device with the problem is set to 1-hour after the real time (maybe).

No issues that I'm aware of. The device/iPhone has not been to other time zones since I'm using iCloud3. Time and time zone on the iPhone is correct. Time and Time zone in HA is also correct. The time the Event Log determines upon restarting the integration is also correct. `Local Time Zone Offset > UTC+01:00 hrs, CET, Country Code-DE`
But the issue with last_located being in the future may actually have started around the latest DST - I can't remember when it started I'm afraid.
The issue with zone_changed being 0000-00-00 00:00:00 has been the same for all devices ever since i started using iCloudV3.

I will get you the logs you requested above in the next days. Really appreciate your help!

**Comment by gcobb321** [comment]
Let me chase this down before you nuke everything.

**Comment by gcobb321** [comment]
Here is the latest rc9 that adds some iosapp setup error checking, provides event log messages if the iosapp (mobile app) trigger and battery sensors are not found and fixes the last_located time error. I've also redone the mobile_app sensor extraction and device matchup so let me know if the iosapp sensors are not matched with the devices correctly.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13688636/icloud3_v3-rc9.zip)

**Comment by klingbing** [comment]
> In iCloud3 _Event Log_ Stage 5 when starting, The iOS app device tracker and sensor entities for each device are listed. There should be a device _tracker, and sensors for Action Trigger, Battery and Notifications. Is Action Trigger listed? It is the sensor.[devicename]_last_update_trigger entity that shows when the phone last issued an update that is generated by the iOS app. If not, check HA Developers Tools for it. Also check the mobile_app Integration for it for the phone and see if it is listed or disabled.
> 
You are on to something! In Event Log Stage 5 `Device Tracker:`, `Action Trigger.:` and `Battery Sensor:` are listed for the iPhone, BUT: they are for a previous name of the troublemaker iPhone: `Tracked Device > iphone_j` is correct, but these above say `Action Trigger.: iphone_6` which was the name of this device in the past. I hadn't noticed this until now.

I then checked the HA Developer Tools for Device Tracker, Action Trigger and Battery Sensor: they do not exist for the troublemaking device, only for my wifes phone (which is working fine)

> Edit line 412 in_icloud3/helpers/time_util.py_ so it reads: `if secs > 0 and utc_local is True: `
> 
I have added this line as suggested and restartet HA.

I will now install the latest RC9 and let you know - thanks!

**Comment by gcobb321** [comment]
I just uploaded a new version of rc9 with that correction and error notifications. It’s the note above your reply. Download and install to see if you get any notifications and errors. The names in the _Event Log_ should have a yellow warning symbol

**Comment by klingbing** [comment]
I have just installed your latest RC9 and restarted HA. There are no warnings whatsoever in Event Log I'm afraid.

**Comment by gcobb321** [comment]
Turn on debug and restart HA. Send me the icloud3-0.log file. Are there any HA error messages in the HA log related to iCloud3 ?
Settings > System > Logs

**Comment by gcobb321** [comment]
It's still not right. There are 00:00:00 last_update_trigger times when there should not be. 

Unzip the following into the _icloud3/support_ directory. 
Make sure Log Level=Debug.
Restart HA.
Let it run for 5-minutes or so and send me the icloud3-0.log file again.

This has a lot of 'trace' statements in it that are dumping a bunch of stuff into the log file that show the state & trigger data as it is processed into the log file

[iosapp_data_handler.zip](https://github.com/gcobb321/icloud3_v3/files/13689873/iosapp_data_handler.zip)

**Comment by gcobb321** [comment]
entity_io will dump the results of the request for the last_trigger data from HA. Unzip it into icloud3/helpers. I think you are still getting a error because icloud3 is not getting the last trigger data. This will tell what is being returnd.
[entity_io.zip](https://github.com/gcobb321/icloud3_v3/files/13692933/entity_io.zip)

iosapp_data_handler is the original version without all the dump data into the icloud3-0.log file
Unzip it into the icloud3/support directory
[iosapp_data_handler.zip](https://github.com/gcobb321/icloud3_v3/files/13692937/iosapp_data_handler.zip)

**Comment by gcobb321** [comment]
OK. The issue is that the _last_update_trigger and _battery_level (and all other iosapp sensors) for you are disabled. I was catching when an iosapp device_tracker was disabled but not the sensors. This has been fixed and iC3 now displays an error/warning when they are not available. iC3 will still use the iOS App for Zone/State changes but not monitor the triggers and battery info.

I have also changed the method of determining the time a trigger takes place and how time zones are handled. Check the Event Log to see if a Trigger or zone change time does not seem to match the event time.

Unzip rc9 and restart as always. See if you get the warning messages, then go and enable those sensors and Restart using Event Log > Actions.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13693706/icloud3_v3-rc9.zip)

**Comment by klingbing** [comment]
I have installed this RC9 and can confirm that I am seeing the error messages you describe. I have enabled these two entities, restarted via Event Log and the errors are gone.

SHOULD the zone_changed being 00:00:00 also be fixed going forward with this resolved?

To conclude: I must have manually disabled _last_update_trigger and _battery_level at some point (these don't disable themselves after all) probably because these were using a no longer active iPhone name. I'll admit it still is confusing to me that entities from an iPhone name used previously are still being used going forward. Could/should these entities maybe be recreated with the new/current iPhone name once this changes? I am sorry for having created such a fuzz about something I have manually changed myself. 

PS. There's a typo in the stage 4 error message "The Mobile App Integration `last_update_trigger` and `bettery_level` (should be battery_level)

**Comment by gcobb321** [comment]
I worked with a user in London a few weeks ago who was also having issues with some of his devices Tracking and others not. In the end, he had disabled the iOS app device_tracker entity of several devices and it took a while to get that problem solved. I added in checks to identify that issue. Yours was similar since it was only sensors that had been disabled but it also pointed out a few bugs on error recovery that needed fixing. I’m glad it’s fixed and you have helped others that will have the same issue. Not to mention the time it will save me since I will not be needed. 

That is what bets testing is for. Thanks

**Comment by gcobb321** [comment]
As it turned out , the zone_changed date/time field was not getting set. That lead me into cleaning up the zone and device distances on the zone_distance and home_distance sensors and fixing an error converting from meters to feet.

Attached is the latest rc9

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13718652/icloud3_v3-rc9.zip)
