### ISSUE TITLE
Home always added to Track-from-Zones (Also-track-from-home-zone: off)

### ISSUE THREAD

**Issue by philrich** [gcobb321/icloud3_v3#237]
Hi,

I have some devices which have set a primary home zone different from home (permanently). These devices should be tracked only from there primary Home Zone, not Home.

I tried to turn off "Special Zones" -> "Also track from Home Zone", but after saving and reentering the config screen, the option is checked again.  I discovered that when i uncheck both, "Primary Base Zone = Home" and "Also track from Home Zone", save and then reenter, "Primary Base Zone = Home" is checked, while "Also track from Home Zone" is unchecked. Weird.

Even with "Also track from Home Zone" unchecked, i am not able to deselect "Home" from a devices "Track from Zones" option. It keeps reappearing after saving. I even tried editing the configuration file but it just ignores this and keeps tracking from home. Am I missing something?

**Comment by gcobb321** [comment]
I have gone over the Primary Track-from-Home Zone Override and made several changes that make it easier and better to use. And it works.

By device:
Set the Zone to track from in the Primary Track-from-Home Zone Override field on the Update Devices screen. It will add that zone to the Track-from-zone selection and make it the Primary Track-from zone. If the Home zone is checked on the Track-from-Zones field, it's tracking results will still be displayed. Uncheck it if you do not need to still track from Home.

Globally on the Special Zones screen:
Check the Primary Track-from-Home Zone Override check-box field to track all devices from the Primary Track-from-Home Zone Override Zone field. Check the Keep Tracking from Home check-box if you want to still see the Home tracking results, otherwise, uncheck it.

This was the final item on the rc9 list. Let me know if it works or you run into anything.

Unzip icloud3_v3-rc9 into the icloud3 directory. 

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13666471/icloud3_v3-rc9.zip)

**Comment by philrich** [comment]
Thanks again. Installing it right now, will report back soon.

**Comment by philrich** [comment]
Removing the superfluous home zone trackers of devices worked flawlessly. One thing I noticed: After some time the home zone trackers were re-added to the devices I removed them. But in the meantime I played with some settings, maybe I re-enabled them by accident. I removed the zones again, will watch this closely the next days.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
