### ISSUE TITLE
Slow zone updates

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#259]
I’m on rc10, but I’ve been noticing this at least since rc9. Either myself or my wife will leave, the event log will show the HA zone changed to away but the ic3 zone won’t change for another 5 minutes or so. 

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/44cd4fcf-e674-49c6-8965-20abb734b7a9)

**Comment by gcobb321** [comment]
I saw the same thing a couple of days ago. What I think is happening is when a device leaves the zone, a scan is done for all devices that do not have the Mobile App. A FamShr locate is requested. But, if the current data for that device (the Watch) was done in the last 2-3 minutes, that data will be used and it stays in the Home zone. I've updated rc10.1 to throw all data away so it will get new data in 15-secs or so.

Download, unzip into icloud3 and restart HA and lets see if that fixes it.
[icloud3_v3-rc10.1.zip](https://github.com/gcobb321/icloud3_v3/files/14074245/icloud3_v3-rc10.1.zip)

**Comment by gcobb321** [comment]
Another thought. The mob app Location is updated but it didn’t issue an exit trigger and the famshr location still shows as being home. Maybe the famshr data did a locate and got a newer Time so that was the data that was used. Can’t tell from just a screen shot of one little Event. The detailed data may show what is going on. 

 Show the tracking monitors which shows the location times from the famshr update. That will show the details (location times from both data sources, gps accuracy, exit triggers, old location errors, etc) to see why things did or didn’t happen.

**Comment by broyuken** [comment]
I just had it happen again, and here were the related logs. I think this might be the problem, but not sure what's causing it. It may be something with the new iOS companion app updates?

![Screenshot 2024-01-30 135608](https://github.com/gcobb321/icloud3_v3/assets/1593391/0fa5158d-582a-482c-ba06-8de39b9fcf41)

**Comment by gcobb321** [comment]
When iCloud3 does not get an Exit trigger but the Mobile App zone go to Away, iC3 checks a few things because the Mobile App does not take GPS accuracy into consideration when it updates it's state value.
1. It may issue a Mobile App location request depending on the age of the data.
2. It looks at the GPS accuracy and will not process the location if it is poor. The end of the 1:48:00 Device Monitor MobAppState-not_n=home), GPS(42.16239, -71.54049/+-100m) shows the accuracy was +-100m which is poor. That 100m means the location reported is outside the zone by 100m when the device is actually inside the zone. The distance of that location is 183m from the zone. iC3 defaults to 65m, less that the default zone size.
3. A location request was probably issued but you didn't include a screenshot of what happened before this message or after it. 

If the Mobile App location was over 200m without an Exit trigger, iC3 would have processed it as if an Exit trigger had been issued.

You could double check everything by creating an automation that does and immediate locate if the Mobile app device_tracker state value goes to not_home and the iC3 device_tracker is still home. Add a delay (1 min) to make sure it is not run before the iC3 device tracker gets to update itself..

The next screen shot would have been interesting to see if the FamShr location was updated with a different location, was updated with the same MobApp location or was not updated because the existing data was being reused because it was updated within the last 2-minutes. Look for those events and post a screenshot of them. It might give mover info on your situation.

**Comment by broyuken** [comment]
These are the 2 directly after it until both show away. 

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/2b239882-85e2-4b8c-8a38-96cd1561913a)

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/c900572d-ddb1-4175-8a48-2cd41fcc95dd)


and these are the 2 directly before it
![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/46555747-404a-4169-a438-3e79ec72e481)

**Comment by gcobb321** [comment]
In this case, there was an Exit Trigger but it still said Outside of Zone without Exit Trigger. Strange.
In both cases, it was Using Nearby Device Results > Brian's Watch

Send me the icloud3-0.log file. It's not in Debug logging but might show something.

Then....
Turn on Debug Logging (Event Log > Start Debug Logging and restart iC3. It looks like you can make this happen when you want. Do that several times with the Outside of Zone message and the MobApp does or does not issue an Exit Trigger, Send me the icloud3-0.log file (geekstergary@gmail.com). 

This code is very very complicated based on location timing, events, other nearby device usage, waiting for and requesting updates and looking at the results.

**Comment by broyuken** [comment]
Why would it use my watch to determine if she's home though? Also I emailed you my log file.

**Comment by gcobb321** [comment]
Ok. Here is rc10.2.

I found a few things and changed the way a few others worked. And found a bug in the iOS Mobile App that was creating problems.
1. Outside of Zone with no Exit Trigger message - Changed the way the Exit Trigger was being logged so this wouldn't be issued when the trigger was actually issued.
2. Passive Zones and the Mobile App - The Mobile App does not issue an Enter Zone Trigger for passive zones (which is correct), but it will issue an Exit Trigger for them (which it should not do). This was creating problems by issuing an Exit Zone Trigger when leaving the real zone and then issuing another Exit Trigger when leaving a zone it had never entered (Passive or otherwise). This Mobile App error is now identified and changed into a Verify Location trigger.
3. Nearby devices - Nearby device info will not be used if the device being updated is in a non-Stationary zone.
4. Other code cleanup.

As always, unzip into icloud3 directory and restart HA.

[icloud3_v3-rc10.2.zip](https://github.com/gcobb321/icloud3_v3/files/14154533/icloud3_v3-rc10.2.zip)

**Comment by broyuken** [comment]
Installed, will let you know if I see improvements. Thanks for the fast response!

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
