### ISSUE TITLE
Link of the cog icon not working

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#261]
Hi Gary! I used to be able to click on the cog icon and go to the integration config page but it’s not working for me anymore. Any other configuration that is needed to be done? Thanks!

![IMG_0273](https://github.com/gcobb321/icloud3_v3/assets/11551691/c563d55a-a02f-4d40-9471-bb964443184f)

**Comment by gcobb321** [comment]
Marcelo, Good to hear from you again. It’s been a while and hope things are going well. 

It works fine for me and no one else has mentioned a problem. It could be a security issue if you are going through any proxy servers or redirects. 

 The gear icon opens a web page at `http://10.0.2.201:8123/config/integrations/integration/icloud3`. This is the same on you would get when you got to Settings > Devices and services > Integrations > iCloud3 > Configure. Go through this link in Chrome or Safari and copy the url and compare it to the one above. I would suspect a https vs http difference. 

There is a parameter on the. Tracking and Other Parameters screen (The last one) that overrides the one I am using. Copy your url into that field and _Event Log > Actions > Restart iCloud3_ to load it. Then see if it works. This may only work on a computer, I’m not sure about from the Mobile App. 

Let me know how it goes. It’s been a while since I looked at that code.

**Comment by marceloaf** [comment]
Hi Gary, good morning! How are you? I’m doing fine! Thanks for asking!

Thanks again for the tip. I do use HA behind Cloudflare. After setting the URL to any of the possible values (Internal or External) worked fine!

Thanks again and have a great week!
Marcelo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by marceloaf** [comment]
I noticed that the relative path also works! It made the trick between the internal and external links...

/config/integrations/integration/icloud3

Best regards,
Marcelo
