### ISSUE TITLE
Error in config_flow.py file - preventing access to configuration menu

### ISSUE THREAD

**Issue by JabberDawg** [gcobb321/icloud3_v3#272]
I was having problems accessing the config menu for stat zones etc - kept getting the following error:

      "user input malformed: extra keys not allowed @ data['srep']"

I think this is due to a typo in the config_flow.py file, in this section...

                vol.Required(CONF_STAT_ZONE_INZONE_INTERVAL,
                            default=Gb.conf_general[CONF_STAT_ZONE_INZONE_INTERVAL]):
                            selector.NumberSelector(selector.NumberSelectorConfig(
                                min=5, max=60, srep=5, unit_of_measurement='minutes')),

The typo is 'srep' should be 'step'.  I corrected this in my local files and the error went away following a restart.  So perhaps this can be fed back into the base code (apols - not sure how to do that ;-)

**Comment by gcobb321** [comment]
That has been fixed in rc10.3 that I uploaded several hours ago. You can get it immediately by going to the GitHub releases page and downloading the icloud3.zip file or waiting for HACS to do the update tonight. You may also be able to refresh HACS by going to it, selecting the 3-dots in the upper right corner and refreshing the information.
