### ISSUE TITLE
Zone update timing

### ISSUE THREAD

**Issue by chupacabra71** [gcobb321/icloud3_v3#274]
Not sure if this is an issue or just a misunderstanding on my part.  I use iCloud3 v3 and have the HA App installed on the wife and my phone.  There is a person tracker for each of us that only uses the iCloud3 sensor.  when i look at the history, it looks like the HA App is very quick to note the zone change, but iCloud3 is somewhat slower (see image)

<img width="1422" alt="HA_location" src="https://github.com/gcobb321/icloud3_v3/assets/9287782/0654eae4-95aa-41b7-a825-e437e426b76f">

I thought iCloud monitors both the iCloud account and the HA app and uses the one that is the most recent.  Maybe i misunderstood?

**Comment by gcobb321** [comment]
iC3 does not look directly at the state value to determine if it changed, it looks at the state update time coming from the device_tracker entity and last_update_trigger entity and sees which one is the latest, and then compares that with the last time. If the current state is newer, it uses that location to determine if an update should be done and where the device is.  The HA App should issue an Exit Trigger when it leaves a zone and an Enter Trigger when it enters one. iC3 picks that up within 5-secs by looking at the last_trigger entity fot a new trigger and the time it changed.

That information is all in the Event Log with more detail in the Event Log > Action > Show Tracking Monitors. What does it show about the MobApp data being used? Are there any items that are rejected because the MobApp issued an exit trigger when the gps accuracy is poor? iCloud3 will discard that one and request a location when that happens.

**Comment by chupacabra71** [comment]
thanks for that explanation.  I do see the enter zone, then immediately there is a "Enter Zone Delayed" for 5 minutes.  

<img width="581" alt="enter-zone" src="https://github.com/gcobb321/icloud3_v3/assets/9287782/ef03208a-fad5-4f03-a36f-835f7d1132cf">

That explains the 5 minute difference on entry of zones for her.

**Comment by gcobb321** [comment]
There is an Enter zone Delay time in the _Configure Settings > Special Zones_ screen that will delay the actual entering of the zone. Mine is set to .5 minutes (30-secs). The purpose is to prevent entering a zone when you might be just driving through it. You might want to r reduce that 5-min time.

**Comment by chupacabra71** [comment]
thanks! I spent a lot of time looking through the individual phone settings, but completely overlooked that section.  I do have a problem that it throws an unknown error when i try to open that menu (see below).  do you want me to open another issue for that? 

<img width="578" alt="Screenshot 2024-02-13 at 6 39 52 AM" src="https://github.com/gcobb321/icloud3_v3/assets/9287782/3e0a708b-8afa-4c23-96f6-e0c43f62b7cb">

**Comment by gcobb321** [comment]
That was fixed in rc10.3

**Comment by chupacabra71** [comment]
d'oh! I thought i was running the latest.  My bad!
