### ISSUE TITLE
iCloud3 v3.0.3 has been released (5/1/2024)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#298]
iCloud3 v3.0.3 is now available on HACS.
Note: If it is not displayed as an available update, select **⠇** in the upper right-corner, then select Update Information.

**Comment by amaisano** [comment]
I am worried about losing a quirk I've been exploiting with 3.0.3. You mention the Battery Charging status has some adjustments.

A problem I've historically had with the Apple Watch battery is that it jumps between charging/not charging all night while it's  on the charging pad. But with a quirk I've been table to determine when it's ACTUALLY on the charging pad or not:

![image](https://github.com/gcobb321/icloud3_v3/assets/688435/ad332897-fa16-4832-b24c-0d6cd8cef829)

_NOTE: The battery remains at 100% regardless of the three states I mention below, so I cannot use that to check unless I wait up to 1 hour for it to deplete to 99%._

`Charging -> NotCharging` = possibly real, probably fake
`Charging -> Not Charging` = real - I've just taken it off the charging pad
`NotCharging -> Not Charging` = real (same as above)

So it's definitely interesting that there are two "not charging" states... but I really rely on this quirk to quickly automate my morning routines (because I pick up my watch from the charger).

**Comment by gcobb321** [comment]
I’ll look at the raw data for the watch and see if I can detect that.

**Comment by gcobb321** [comment]
@jayscovill 
1. What are you referring to by the 'Update Information option'?
2. What are you trying to do? 
3. What update notification are you trying to get?

**Comment by jayscovill** [comment]
The update to v3.0.3 doesn't appear in HACS.

**Comment by JtwoA** [comment]
> The update to v3.0.3 doesn't appear in HACS.

You aren't on the developer version, I take?

![image](https://github.com/gcobb321/icloud3_v3/assets/12992040/1daff006-d29a-4e48-82d8-143fe4047adb)

**Comment by jayscovill** [comment]
> > The update to v3.0.3 doesn't appear in HACS.
> 
> You aren't on the developer version, I take?
> 

No, didn't see it mentioned anywhere it was the development version only release.  Thanks for the clarification.

**Comment by gcobb321** [comment]
I put it in the Developers Version and immediately noticed an error adding devices that those users would not see but the regular report would. It will probably be updated today or tomorrows

**Comment by gcobb321** [comment]
iCloud3 v3.0.4 was uploaded on 5/7 and is now available on HACS.
