### ISSUE TITLE
EventType is deprecated alias

### ISSUE THREAD

**Issue by GerdRuetten** [gcobb321/icloud3_v3#300]
Hi,

under HA-Version 2024.5.1 and iCloud3-Version v3.0.3 i get following warning in the HA-Log:

`EventType was used from icloud3, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'icloud3' custom integration
`
OK, you have 1 year time to fix it :-D

Best regards
Gerd

**Comment by gcobb321** [comment]
It's been fixed in the next release. I am waiting for a couple of things to check out before it is sent out.

Here is an early copy if you want to install it. There will be at least one more change before I send it out. 

Unzip it into the iCloud3 directory and restart HA.
[icloud3 v3.0.4.zip](https://github.com/gcobb321/icloud3_v3/files/15226776/icloud3.v3.0.4.zip)

**Comment by GerdRuetten** [comment]
I test it tomorrow and give you feedback

**Comment by gcobb321** [comment]
V3.0.4 is available on HACS. It is a little newer than the one attached above
