### ISSUE TITLE
Question About Migrating to iC3 HACS

### ISSUE THREAD

**Issue by riedlem** [gcobb321/icloud3_v3#327]
Sorry if this is a dumb question. 
So I migrated to iC3 back when it was first released by manually installing the new files. 
Is there any specific process to follow to get off of the manual files and over to HACS installing?

I saw documentation for migrating to the new version from the old version, but didn’t see documentation for that, and unsure if I need to remove everything and start over fresh or if there’s a way to keep all the current configs.

**Comment by gcobb321** [comment]
You should be fine installing iCloud3 v3 from HACS. It is suppose to migrate the data OK but it has been a while since I tested that code. After you do the migration, go into the Configuration > Update Devices screen. They will be set to Inactive. Change to Tracking and save the device info. If you run into any problems, delete all the devices and readd them.

**Comment by riedlem** [comment]
Everything appeared to be in order after updating the app in HACS
