### ISSUE TITLE
SyntaxWarning on iCloudv3 startup

### ISSUE THREAD

**Issue by chupacabra71** [gcobb321/icloud3_v3#386]
I'm still seeing the error below on the logs as i start up.  does not seem to cause any issues with functionality, but thought i would share.  

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/icloud3/helpers/entity_io.py:259
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 1:22:32 PM (2 occurrences)
Last logged: 1:22:32 PM

<string>:1: SyntaxWarning: invalid escape sequence '\s'
```

**Comment by gcobb321** [comment]
I have looked for that code more than once and have never found it. That line of code is reformatting records from the entity registry into a useable table. I'll see if there is another way to do it that does not generate the message. I can not create it since it depends on the data in your entity registry.

**Comment by chupacabra71** [comment]
i assume it is the naming of some entity that has nothing to do with iCludv3.  I will close it as i don't see any issues with the integration.  i will attempt to dump the list of entities and use your formatting to see if i can figure which one it is.  thanks again for all you do for the community!
