### ISSUE TITLE
Conflict between phone and watch location 

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#46]
I went for a run tonight with my Apple Watch (with e-sim) and left my phone at home. 
I have the watch ic3 and iPhone ic3 device trackers set up and linked to my person.bruce
As each device checked in it would toggle me from home / away / home / away etc. 

Any thoughts on the best way to handle this. 
ideally ic3 would know that my watch was moving and my phone wasn’t. So wouldn’t update the tracker on my phone. 
Particularly if my phone was on charge. 

Thinking out loud. 
I guess I could add an automation that when my phone goes on charge it disables updates on iCloud3 location until it comes off charge ?
Is that possible ?

Anyone have thoughts on how this should best be handled ?

thanks.

**Comment by marceloaf** [comment]
Personally, I've been using just my watch as a device tracker on the person entity. It's been working ok. Although I had occasions where my entire apartment turned off at night because the watch was incorrectly marked as Away and some automations were triggered. After I figured it out, I laughed... :-) The moment it occurred, TV and a lot of lights were on and the apartment gone completely off. I thought we were having some energy outage... 

device trackers have the consider_home option but I think is appropriate for wifi based ones, not gps. That's the advantage of having another device tracker in the person entity but as I very often leave just with my watch, having both phone and watch will not work for me.

If you think in some other solution, let me know...

Regards

**Comment by gcobb321** [comment]
A while back, I had fields for 2 FamShr devices tied to one ic3 device but never implemented it. I needed to get ic3 done without adding another level of complexity. That is something I'll probably address in the future but it will be a while.

**Comment by B-Hartley** [comment]
Is there a service call in ic3 that will disable location updates ?
Or should I use a device_tracker pause type command?
Would that work ?

**Comment by gcobb321** [comment]
iC3 Service Calls

pause device:
```
service: icloud3.update
data:
  command: pause
  device_name: gary_iphone
```
pause all
```
service: icloud3.update
data:
  command: pause
```

resume is the same format as above. Change pause to resume

**Comment by B-Hartley** [comment]
Perfect thanks. 
milk set it to pause updates when a device is on a charger. 
need to look at charging statuses. 
news to check I can tell it is on charger even when it reaches 100 %.

**Comment by gcobb321** [comment]
I fixed some things related to battery/ charging in b9

**Comment by gcobb321** [comment]
I'll close this for now but will investigate setting up a person, etc.
