### ISSUE TITLE
"Stationary" zone seems to be overriding a named zone from config file

### ISSUE THREAD

**Issue by beyondwatts** [gcobb321/icloud3_v3#55]
"Stationary" zone seems to be overriding a named zone from the homeassistant configuration file. Instead of seeing person is at "NamedZoneFromConfigFile", I am seeing the person is at "Stationary".

Looking in the logs:
- I see the "person was detected at Stationary" event
- do not see an event for entering the NamedZoneFromConfigFile defined in the config file.
- Interestingly, I do see an event for a zone that was created in the UI -> "person was detected at NamedZoneFromUI" on the way past that zone.

Please let know any additional information I can provide to assist

**Comment by gcobb321** [comment]
I have not used the NamedZoneFromConfigFile. My zones are set up from the UI in Devices & Settings > Areas &Zones. Another user said the zones from the config file were not picked up by iCloud3. He added the zone to the UI and it was then detected. It was on my list to look at but you might want to try setting it up from the UI and see if that solves the problem.

**Comment by gcobb321** [comment]
I just uploaded beta11p1. [Get it here](https://github.com/gcobb321/icloud3_v3/blob/main/ic3-beta-11p1.zip)..

It addresses the Stationary zone name in the device_tracker state field. It does not address zones that are in the configuration.yaml file (probablu UI only) but I found a few things happening with the Stationary zone name that were not correct.
- Zone state in Developer Tools being set to 'zoning' instead of a counter and the Friendly Name attribute was not correct.
- The Device tracker state friendly name was also not being taken from the name field on the Special Zones configuration screen.

I  added a Stationary Zone friendly name parameter on the iCloud3 Update Device screen. Now each device's stationary zone is fully customizable. I'm using GaryZone and LillianZone instead of GarStatZone & LilStatZone or just Stationary. Lillian's watch is also set to LillianZone and it is getting picked up by the person.lillian entity.

This is a preliminary beta 11.

**Comment by beyondwatts** [comment]
Thanks - I moved the zones to UI and saw the same issue. I did manage to get it to detect the zone once in debug mode (and wondered if there is any caching?) but otherwise it was not detecting zones. 

Thanks for the update - will keep experimenting

**Comment by gcobb321** [comment]
Turn log level debug on, restart HA and let it run for a while until you think it should be in a stationary zone but isn’t. Then send me the iCloud-debug.log file and I’ll take a look as to what is going on. Email to geekstergary@gmail.com. Nothing is cached. 

in the Event Log, does it show an’into StatZone@hhmmss time? If there is much movement, the start zone timer is reset and it tries again when the Still Time has expired with no movement. It shows  the distance moved and the times in the Results message

**Comment by beyondwatts** [comment]
Beta 10 is working with debug log level today. Will update to Beta 11 and keep you posted

```
Tracking Results: From-Home > iOSAppZone-home, iC3Zone-school, Interval-10 min, TravTime-, Dist-1.1 km, NextUpdt-16:25:35, MaxDist-0 km, Dir-in_zone, Moved-0m, Battery-28%, LastDataUpdate-16:15:21, GPSAccuracy-8m, LocAge-31 sec ago, OldThreshold-2 min, LastEvLogMsg-16:15:38, Method-1.EnterZone
```
