### ISSUE TITLE
What's the equivalent service in v3 to icloud3_set_interval?

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#59]
Hi Gary, how are you? Hope this finds you well..

What's the equivalent service in v3 to icloud3_set_interval (v2.4.7)? Is this now an option of the icloud3.action service? I was not able to locate this info in v3 documentation.

![image](https://user-images.githubusercontent.com/11551691/216676942-55fd9dab-11be-4ca0-a9be-94e84b2c62b3.png)

**Comment by gcobb321** [comment]
That service haw been removed from v3. There is no equivalent. You can set the inzone interval on each device.

What is it you were trying to do?

**Comment by marceloaf** [comment]
I currently have v3 and v2.4.7 running for testing purposes and I can't make v3 get more precise positions as I can do in v2. In each environment I have my person entity where my apple watch (with cellular) is the tracked device. See examples below how v3 is less precise although I have the same inzone interval in both environments (10 minutes). With v2 I can make it make it update more often if I leave home whereas in v3 I can't. In the example 

**Left for 1h20min
v3 (11p1):**
![2023-02-03 (1)](https://user-images.githubusercontent.com/11551691/216790597-93d47ad4-fce5-4eb0-8893-5e113ce4ce45.png)

**versus v2.4.7**
![2023-02-03](https://user-images.githubusercontent.com/11551691/216790617-76317ec5-e2d7-41bf-b710-9791f7cfa49a.png)


**Another example where I left for just 30min to walk with dogs.
v3:**
![2023-02-02 (3)](https://user-images.githubusercontent.com/11551691/216790670-777af281-3170-46b3-9099-fb7512d1d947.png)

**v2.4.7:**
![2023-02-02 (2)](https://user-images.githubusercontent.com/11551691/216790678-2d19980e-9f6a-4294-8a43-bc6c09bf9c35.png)

**Comment by gcobb321** [comment]
Look at the Event Log results for v2 and v3 to see the interval between each tracking request. It also shows how the data is being processed, old location retries, distance moved,  devices near by, etc. even though you are comparing the same device, the data returned from iCloud May be different as it responds to each location request. One might be polling on a fixed basis where the other it’s being more battery efficient by polling on a less frequent interval. 

For comparisons and questions about what iCloud3 is doing, you have to look at the device tracker entity that iCloud3 updates instead of the person entity which ha controls and might be getting data from different sources.

**Comment by marceloaf** [comment]
Even monitoring the icloud3 device directly instead of the person entity there, is still a huge difference in v3 data... In this experiment I turned off every automation in v2.4.7 that would be requesting more frequent updates.

The example below represents 3h30 minutes out of home. At 15:45h v3 is still showing me as if I were at my sister's house. It has more than 15 min I'm home.... 
![2023-02-05](https://user-images.githubusercontent.com/11551691/216838859-a604f279-9fda-475d-bdf9-6d2342776d10.png)

v2.4.7:
![2023-02-05 (1)](https://user-images.githubusercontent.com/11551691/216838881-2f55f2dd-0322-456e-83b3-aeac47245a99.png)

**Comment by JtwoA** [comment]
I’m noticing similar delays in position reporting.  Often I need to manually refresh to make iC3 realize I am actually home again.OwnTracks has already “signed off” on verification by that point.On Feb 5, 2023, at 13:52, marceloaf ***@***.***> wrote:﻿
Even monitoring the icloud3 device directly instead of the person entity there, is still a huge difference in v3 data... In this experiment I turned off every automation in v2.4.7 that would be requesting more frequent updates.
The example below represents 3h30 minutes out of home. At 15:45h v3 is still showing me as if I were at my sister's house. It has more than 15 min I'm home....

v2.4.7:

**Comment by gcobb321** [comment]
Are you using the iOS app? 

I am and am getting significant update triggers constantly. Also Zone enter/exit triggers. Without the iOS app, everything depends on iCloud3 requesting a new location based on the interval, which can be quite long depending on the distance from home.

**Comment by JtwoA** [comment]
That’s where it’s weird:  in the Event Viewer it shows App as home but iC3 as away.  I’m using the app zone to trigger automations.

**Comment by gcobb321** [comment]
In the Event Log, does it show any triggers  from the iOS app? Zone enter/exit or significant location changes or background refresh? Does the iOS zone always show Home or does it show Away when you leave home?

The iOS device_tracker entity name and the last_update _trigger entity sensor that is monitored is displayed when iCloud3 starts. Are both versions monitoring the same sensors?

In v3, you can select the iOS app d_t for an iCloud3 device on the configuration > Update Device screen. It can scan for an iOS app device or you can select the one to monitor. ? Does everything look correct there?

**Comment by gcobb321** [comment]
When you were using the set_interval service call, when were you calling it and how were you triggering it. Time? Distance? Location? Obviously, I can put it back in without any problem. I can also add another interval time override by device or in general so every device does a locate every 10 or 15 or xx minutes. 

Will that help. Trying to understand what is going on and the best way to fix it. 

It might help if I looked at the Event logs from v2 and v3 for the same time period.

**Comment by marceloaf** [comment]
> When you were using the set_interval service call, when were you calling it and how were you triggering it. Time? Distance? Location? Obviously, I can put it back in without any problem. I can also add another interval time override by device or in general so every device does a locate every 10 or 15 or xx minutes.
> 
> Will that help. Trying to understand what is going on and the best way to fix it.
> 
> It might help if I looked at the Event logs from v2 and v3 for the same time period.

I call the service as soon as I'm first detected out of home, lowering the interval to 5 min, as long as I'm X Kms from home (calc_distance). If my distance gets further than that, I return to the default value or even increase it if I'm too far.

It would be nice if you could return this service but notice that, in the example I posted above, I didn't use it. In other words, v2 checks much more frequent that v3. I understand that it might help in battery saving but I still would like to be able to adjust it a little bit according to my distance from home.

And answering your initial questions, I'm tracking an apple watch, without ios app. The inzone interval is set for the same value(10 min) in the examples above.

**Comment by marceloaf** [comment]
I'm sending you an e-mail with the logs in a few minutes. Thanks in advance!

**Comment by gcobb321** [comment]
When the results are displayed in the Event log (right below the summary line with the iosapp zone, ic3 zone, interval, distance and travel time), it shows the 'Method' used to determine the interval. When a zone is exited, the interval is set to 4-min if it is a home zone or if received an exit trigger from the ios app. It is set to 2-min otherwise.

The watch will not know it exited the zone until the next poll, it will not get a trigger. It will then use the regular method to get the interval as other devices based on distance and travel time. You said you call a soon as you detect you are out of the one to get everything going. What determines you are out of the zone (wifi disconnect, owntracks, etc). I can add the set_interval back without any problems. Another question would be should the interval be based on the normal way it is determined or, if the ios app is not installed, do not exceed the inzone interval (watch might be say 10-15 minutes to pick up when you enter a zone?

**Comment by gcobb321** [comment]
I'll be uploading b11 soon and will then have time to look at it further.

**Comment by gcobb321** [comment]
Beta 12
~~~~~~~~~~~~~~~~~~~~
Added the 'locate' Action to the icloud3.action Service Call. This action lets you locate a device  (or all devices) immediately or in after a specific time has elapsed. This replaces the set_interval service call in v2.

    The following examples explains how it can be used:
        Calling method:
            service: icloud3.action
            data: {action: locate xx min, device_name: xxx}

        Examples:
            - Locate gary_iphone in 4 minutes: {action: locate 4 min, device_name: gary_iphone}
            - Locate gary_iphone immediately:  {action: locate, device_name: gary_iphone}
            - Locate all phones in 4 minutes:  {action: locate 4 min}
            - Locate all phones immediately:   {action: locate}

Unzip service_handler.zip into the icloud3/support directory

[service_handler.zip](https://github.com/gcobb321/icloud3_v3/files/10668530/service_handler.zip)
