### ISSUE TITLE
Can’t change the device_tracker state format setting

### ISSUE THREAD

**Issue by myMartek** [gcobb321/icloud3_v3#67]
I am using Beta 12 and have issues with the setting for setting device tracker state format. 

It always shows as invalid regardless which option I choose.

![AEB8467D-EC50-4480-B2EC-F1D82B07D7F4](https://user-images.githubusercontent.com/3337806/218282740-577a7f4f-59d6-4d1c-96bd-5273348d4336.jpeg)

**Comment by gcobb321** [comment]
Open the _.storage/icloud3/configuration_ file and look at the _"device_tracker_state_format"_ parameter. It should be "zone" or "fname". That parameter was updated during the install of beta 12. I wonder if it did not get updated?

If the parameter does not exist, insert `"device_tracker_state_format": "zone"` after the `display_zone_format parameter`

**Comment by myMartek** [comment]
Actually it’s not even in there. I updated from Beta 8 or 9 (can’t remember) I guess this was simply a bug related with skipping in between updates. 

Can you tell me in wich Object path this option needs to be exactly? The I will add it manually. 

Strange is, that it is not added when using the config ui. In theory it should add missing values automatically I would say.

**Comment by gcobb321** [comment]
When iCloud3 starts, it checks the config file to see if there are any parameter additions or changes.  I was checking a parameter added in beta10, converting it to a new format and deleting the old parameter. I hadn't considered that it might have never been added. This i fixed in the following module.

Unzip config_file.zip into icloud3/support directory and restart ha.

[config_file.zip](https://github.com/gcobb321/icloud3_v3/files/10716554/config_file.zip)
