### ISSUE TITLE
Home Distance sensor interprets m as km as soon as the distance drops to <1km 

### ISSUE THREAD

**Issue by t077584** [gcobb321/icloud3_v3#82]
If driving home, the Home Distance sensor seems to work just fine as long as one is more than 1km away from home. The minute it is below 1000m, the sensor reports the meter back as km, resulting in useless data for automations. In below example, the last correct point was measured at 1.5km from home. The next measure was at 580m, but the sensor gives back 580km.

The Zone Distance sensor seems to work correctly though.

![2023-03-09_16-01-12](https://user-images.githubusercontent.com/121488015/224064917-c5a95678-2450-4be5-b6dd-290d047f04cb.png)

**Comment by gcobb321** [comment]
This has been fixed in beta 14, along with a bunch of other improvements to distance sensors.

From a quick trip a few minutes ago. Zone and Home distance sensors both report the same distances.
![image](https://user-images.githubusercontent.com/35449479/224078180-78fe0300-892d-484a-bc67-47545b7860fa.png)

Precision for the state value is 2-decimal places and 4(or 5) for the attibute distances. Plus the meters_distance and miles_distance attributes.
![image](https://user-images.githubusercontent.com/35449479/224078827-ca7c7b43-702a-48ca-a0b9-dd6a7614ca9d.png)
